language: java

jdk: openjdk8


before_install:
  - sudo apt update
  - sudo apt install openjfx
  - sudo apt install mysql-workbench	

install: true
 

addons:
  sonarcloud:
    organization: "evoi95"
    token: "b6cbe4f702860b5e27a50764e0f1380eda19616a" # encrypted value of your token

services:
  - mysql

script:
  - ant build
  - sonar-scanner
