language: java

jdk: openjdk8

services:
  - xvfb    

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - export DISPLAY=:99.0

install: true


addons:
  sonarcloud:
    organization: "evoi95"
    token:
      secure: "345aa28f0b7412d4276992231e3ebe48b940f8d3" # encrypted value of your token

script: 
  - ant build
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
