language: java

jdk: openjdk11

services:
  - xvfb    

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - export DISPLAY=:99.0

install: true


addons:
  sonarcloud:
    organization: "evoi95"
    token: "b6cbe4f702860b5e27a50764e0f1380eda19616a" # encrypted value of your token

script:
  - ant build
  - sonar-scanner
